### ISSUE TITLE
[BUG] Fehler auf der interaktiven Karte

### ISSUE THREAD

**Issue by Beastscream** [Zayon-Network/Zayon-Network#3]
**Beschreibe den Bug**
Diamantblockstrukturen sind auf der Karte an Stellen, wo sie nicht sind.

**Zum Reproduzieren**
Schritte um den Bug zu reproduzieren:
1. Gehe zu 'https://zayon.de/gamemode/lobby/map'
2. Bug entsteht

**Screenshots**
Wenn du screenshots hast, kannst du diese hier gerne anhängen.
![Bug](https://user-images.githubusercontent.com/78698189/107154531-b7c18280-6973-11eb-8b93-ab7acbeb487b.png)

**Client Information (bitte fülle die weiteren Informationen aus):**
 - Texturepack:  default]
 - Version [z.B. 1.16.5]

**Wo ist der Bug aufgetreten?**
Website

**Weiterer Kontext**
Hast du noch weitere Informationen? Dann kannst du sie hier ablegen.

**Comment by NIkiIncredible** [comment]
Fehler nicht mehr relevant
