### ISSUE TITLE
[BUG] Pferde im Boden

### ISSUE THREAD

**Issue by Beastscream** [Zayon-Network/Zayon-Network#4]
**Beschreibe den Bug**
Pferde, die im Boden stecken (Ich behaupte einfach mal so frei, dass man sich da drauf setzen soll, und sie dann nicht sehen soll)

**Zum Reproduzieren**
Schritte um den Bug zu reproduzieren:
1. Gehe zu 'KnockKnock Spielmodus'
4. Sehen und staunen

**Screenshots**
Wenn du screenshots hast, kannst du diese hier gerne anhängen.
![2021-02-07_18 47 40](https://user-images.githubusercontent.com/78698189/107154761-00c60680-6975-11eb-8797-5b894dc24afd.png)

**Client Information (bitte fülle die weiteren Informationen aus):**
 - Texturepack: default
 - Version [z.B. 1.16.5]

**Wo ist der Bug aufgetreten?**
KnockKnock-Spielmodus Umgebung

**Weiterer Kontext**
Hast du noch weitere Informationen? Dann kannst du sie hier ablegen.

**Comment by NIkiIncredible** [comment]
Fehler behoben.
